### ISSUE TITLE
Branches and versions on Zanata

### ISSUE THREAD

**Issue by piotrdrag** [misli/fedora-software#17]
Currently there is a Zanata "version" for every release [1]. I know it might be counter-intuitive, but "version" should correspond to a branch, not a release. So, in the case of fedora-software, there should be only one "version", master.

[1] https://fedora.zanata.org/project/view/fedora-software/versions

**Comment by jmlich** [comment]
I am not very skilled with zanata. I didn't want to delete someones work when new "release" came. I would like to have something like direct connection between zanata and github, but I don't know if it is even possible.

**Comment by piotrdrag** [comment]
I'm not exactly sure what you mean. Maybe you should contact the Zanata guys with your use-case?

Anyway, the reported issue seems fixed. It would be nice if you could periodically pull translations from Zanata. Since the last time (four months ago), three languages has been added, and some has been 100% completed.

**Comment by jmlich** [comment]
I am not able to do it regularly, but feel free to open new issue when you need rebuild for your language. I will try to merge your changes as soon as possible.
